import type { IPhase } from ".";
export interface IModule1Phase extends IPhase {
  html: string;
}
export const module1Phases: IModule1Phase[] = [
  {
    id: 1,
    property: "elemento { /n propriedade: valor; /n }",
    name: "Sintaxe Básica",
    description: "O Objetivo básico do CSS é permitir que um motor do navegador pinte elementos na página com características específicas como cores, posições, ou decorações. A sintaxe CSS reflete estes objetivos e seus blocos de contrução básicos são:/n- A propriedade é um identificador que possui um nome legível, que define o que será considerado ou editado./n- O valor descreve como o recurso será tratado pelo motor. Cada propriedade possui um conjunto de valores válidos, definida por uma gramática formal, bem como um significado semântico.",
    instructions: "Selecione todas as tag ##<poção>##.",
    board: "mrr",
    after: "{ /n/tabseu-estilo-aqui: valor; /n }",
    html: "<div class=”office”>/n/tab<prateleira id=”alta”>/n/tab/tab<poção></poção>/n/tab/tab<poção class=”azul”></poção>/n/tab</prateleira>/n/tab<prateleira>/n/tab/tab<poção class=”azul”></poção>/n/tab</prateleira>/n/tab<mesa>/n/tab/tab<poção></poção>/n/tab</mesa>/n</div>",
    solution: "potion"
  },
  // {
  //   id: 2,
  //   property: "B",
  //   name: "Seletores de Classe",
  //   description: "Use classes CSS para estilizar grupos de elementos.",
  //   instructions: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   board: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   before: ".destaque { }",
  //   after: ".destaque { font-weight: bold; }",
  // },
  // {
  //   id: 3,
  //   property: "C",
  //   name: "Seletores de ID",
  //   description: "Selecione um elemento único pelo seu ID.",
  //   instructions: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   board: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   before: "#titulo { }",
  //   after: "#titulo { font-size: 2rem; }",
  // },
  //   {
  //   id: 4,
  //   property: "A",
  //   name: "Seletores de Tipo",
  //   description: "Aprenda a selecionar elementos HTML pelo nome da tag.",
  //   instructions: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   board: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   before: "p { }",
  //   after: "p { color: red; }",
  // },
  // {
  //   id: 5,
  //   property: "B",
  //   name: "Seletores de Classe",
  //   description: "Use classes CSS para estilizar grupos de elementos.",
  //   instructions: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   board: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   before: ".destaque { }",
  //   after: ".destaque { font-weight: bold; }",
  // },
  // {
  //   id: 6,
  //   property: "C",
  //   name: "Seletores de ID",
  //   description: "Selecione um elemento único pelo seu ID.",
  //   instructions: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   board: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   before: "#titulo { }",
  //   after: "#titulo { font-size: 2rem; }",
  // },
  //   {
  //   id: 7,
  //   property: "A",
  //   name: "Seletores de Tipo",
  //   description: "Aprenda a selecionar elementos HTML pelo nome da tag.",
  //   instructions: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   board: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   before: "p { }",
  //   after: "p { color: red; }",
  // },
  // {
  //   id: 8,
  //   property: "B",
  //   name: "Seletores de Classe",
  //   description: "Use classes CSS para estilizar grupos de elementos.",
  //   instructions: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   board: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   before: ".destaque { }",
  //   after: ".destaque { font-weight: bold; }",
  // },
  // {
  //   id: 9,
  //   property: "C",
  //   name: "Seletores de ID",
  //   description: "Selecione um elemento único pelo seu ID.",
  //   instructions: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   board: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   before: "#titulo { }",
  //   after: "#titulo { font-size: 2rem; }",
  // },
  //     {
  //   id: 10,
  //   property: "A",
  //   name: "Seletores de Tipo",
  //   description: "Aprenda a selecionar elementos HTML pelo nome da tag.",
  //   instructions: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   board: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   before: "p { }",
  //   after: "p { color: red; }",
  // },
  // {
  //   id:11,
  //   property: "B",
  //   name: "Seletores de Classe",
  //   description: "Use classes CSS para estilizar grupos de elementos.",
  //   board: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   instructions: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   before: ".destaque { }",
  //   after: ".destaque { font-weight: bold; }",
  // },
  // {
  //   id: 12,
  //   property: "C",
  //   name: "Seletores de ID",
  //   description: "Selecione um elemento único pelo seu ID.",
  //   board: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   instructions: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   before: "#titulo { }",
  //   after: "#titulo { font-size: 2rem; }",
  // },
  //   {
  //   id: 13,
  //   property: "A",
  //   name: "Seletores de Tipo",
  //   description: "Aprenda a selecionar elementos HTML pelo nome da tag.",
  //   instructions: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   board: "Selecione todos os parágrafos e deixe o texto vermelho.",
  //   before: "p { }",
  //   after: "p { color: red; }",
  // },
  // {
  //   id: 14,
  //   property: "B",
  //   name: "Seletores de Classe",
  //   description: "Use classes CSS para estilizar grupos de elementos.",
  //   instructions: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   board: "Selecione os elementos com a classe .destaque e aplique negrito.",
  //   before: ".destaque { }",
  //   after: ".destaque { font-weight: bold; }",
  // },
  // {
  //   id: 15,
  //   property: "C",
  //   name: "Seletores de ID",
  //   description: "Selecione um elemento único pelo seu ID.",
  //   instructions: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   board: "Selecione o elemento com id #titulo e aumente o tamanho da fonte.",
  //   before: "#titulo { }",
  //   after: "#titulo { font-size: 2rem; }",
  // },
];